server:
  port: 8710
eureka:
  client:
    serviceUrl:
      defaultZone: http://111.229.54.132:8882/eureka/
spring:
  application:
    name: goods
  redis:
    commandTimeout: 5000
    pool: 
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
    cluster: 
      #设置key的生存时间，当key过期时，它会被自动删除；
      expire-seconds: 120
      #设置命令的执行时间，如果超过这个时间，则报错;
      command-timeout: 5000
      #设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址;
      nodes: 121.199.35.56:6379,212.64.55.141:6379,111.229.54.132:6379
  datasource:
        name: test
        url: jdbc:mysql://111.229.54.132/product  #连接语句记得更改
        username: tzr
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  #对应实体类路径
  type-aliases-package: com.tfye.entity
  #对应mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml
  
  