server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8882/eureka/
spring:
  redis:
    host: 111.229.54.132
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  application:
    name: message
  activemq: 
    broker-url: tcp://212.64.55.141:61616
    in-memory: true
    pool:
      enabled: false
  mail:
  #    host: smtp.qq.com
  #    username: 3532749049@qq.com
  #    password: bnvtcpkaujnkcjaa 
      password: ZDNRCEJAXJLSRLJK
      username: wdzfwa@163.com
      host: smtp.163.com
      default-encoding: UTF-8
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
   